version: '3.1'

services:
    leaderboard-container:
        container_name: leaderboard-container
        build:
            context: .
        image: leaderboard-image
        ports:
            - 5000:5001
        networks:
            - custom_network

    redis-container:
        container_name: redis-container
        image: redis
        ports:
            - 6379:6379
        networks:
            - custom_network

networks:
    custom_network:
        external: true
